{
  let view={
    el:'#siteLoading',
    show(){
      $(this.el).addClass('active')
    },
    hide(){
      $(this.el).removeClass('active')
    }
  }
  let controller={
    init(view){
      this.view=view
      this.bindEventHub()
    },
    bindEventHub(){
      window.eventHub.on('uploading',()=>{
        this.view.show()
      })
      window.eventHub.on('uploaded',()=>{
        this.view.hide()
      })
      window.eventHub.on('uploadCover',()=>{
        this.view.hide()
      })
    }
  }
  controller.init(view)
}